### ISSUE TITLE
Major release before #94?

### ISSUE THREAD

**Issue by kescobo** [JuliaStats/MultivariateStats.jl#102]
Thanks to #85, I'm removing a bunch of bespoke methods from my own package (https://github.com/BioJulia/Microbiome.jl/pull/31) in favor of the ones here, and I've also created plot recipes that depend on the changes (https://github.com/JuliaPlots/StatsPlots.jl/pull/230). 

Unfortunately, there doesn't seem to be a way to depend on unreleased versions of this package (which I suppose makes sense). Given that there's clearly a lot to do prior to merging and releasing #94 , I was wondering if you'd be willing to release a `0.7` before that? I assume doing a minor `0.6.1` release is technically a violation of semver. 

If not, I totally understand as there's a lot on your plate, just thought I'd ask :-)

**Comment by wildart** [comment]
It looks like there will be a couple of more releases before 1.0.0.

**Comment by kescobo** [comment]
Oh, excellent. I'll be on the lookout :-)

**Comment by kescobo** [comment]
Any chance this could happen sooner rather than later? I'm stalled on a couple of fronts waiting on #85 to be in a tagged release.

**Comment by rofinn** [comment]
Made a PR to bump the minor version https://github.com/JuliaStats/MultivariateStats.jl/pull/106

**Comment by wildart** [comment]
@JuliaRegistrator register()
