### ISSUE TITLE
Outdated document of PCA.

### ISSUE THREAD

**Issue by Losses** [JuliaStats/MultivariateStats.jl#107]
The DataArrays is no longer maintained, constructing dataset should use

```
Xte = convert(Matrix,iris[2:2:end,1:4])'
```
but not:
```
Xte = convert(Array,DataArray(iris[2:2:end,1:4]))'
```

**Comment by nalimilan** [comment]
Thanks for the report. Would you make a pull request to fix this? You can edit the file directly on GitHub.

**Comment by Losses** [comment]
@nalimilan Okay, I'll do it this weekend if I have enough free time :D

**Comment by fratrik** [comment]
It looks like the edit is in github:

https://github.com/JuliaStats/MultivariateStats.jl/blob/master/docs/source/pca.rst

but hasn't made its way to the documentation:

https://multivariatestatsjl.readthedocs.io/en/latest/pca.html
