### ISSUE TITLE
PCA example in the docs doesn't work because DataArray is no longer viable

### ISSUE THREAD

**Issue by glwhart** [JuliaStats/MultivariateStats.jl#120]
I tried to run the example of the iris dataset in the PCA section of the docs and it wouldn't run because DataArray is no longer part of the Julia language, apparently.

**Comment by wildart** [comment]
It looks like the docs haven't been updated after the fixes. Look for example here: https://github.com/JuliaStats/MultivariateStats.jl/blob/master/docs/source/pca.rst

**Comment by Jona-Engel** [comment]
> It looks like the docs haven't been updated after the fixes. Look for example here: https://github.com/JuliaStats/MultivariateStats.jl/blob/master/docs/source/pca.rst

Could you clarify which fixes? 
The `transform` call does not work for me.
Are their any unmentioned dependencies which we should import as well?

**Comment by wildart** [comment]
Ah! It seems that `RDatasets` has `transform` method now, which is a reexport from `DataFrames`. This causes a clash. Try to add module prefix as follows:

``` julia
Yte = MultivariateStats.transform(M, Xte)
```

**Comment by wildart** [comment]
The example has been updated in the new documentation. Please, [take a look](https://juliastats.org/MultivariateStats.jl/stable/pca/#Example).
