### ISSUE TITLE
Documentation separate from code

### ISSUE THREAD

**Issue by cyianor** [JuliaStats/MultivariateStats.jl#128]
Hi,

I am writing a pull request to propose to include factor rotations into MultivariateStats.jl and was wondering if there is a concrete reason why this package doesn't use Documenter.jl's capability to create documentation from the source code. I personally like the GitHub source code links it adds and the formatting gets a bit more uniform with respect to Base Julia's documentation packages as well. It also seems to me that it is easier to forget to update the separate documentation than the documentation directly in the source code.

**Comment by wildart** [comment]
The reason is the lack of resources. You are welcome to present in the documentation as docstrings which I hope the future will be incorporated in a proper Documenter based docs.

**Comment by wildart** [comment]
Documenter docs available from v0.9.0.
