### ISSUE TITLE
Does this library welcome implementing some robustified PCAs?

### ISSUE THREAD

**Issue by nobuta05** [JuliaStats/MultivariateStats.jl#129]
I'm not sure which library I should submit PR. So I would be grateful if you give an opinion.

I think it would be desirable to have a variety of PCAs available in the Julia lang. Robustified PCAs are ones of these I can implement.

Does this library welcome a PR for implementing some robustified PCAs such as RPCA-OM(Nie et al., 2014, "Optimal mean robust principal component analysis"), REAPER(Lerman et al., 2015, "Robust computation of linear models by convex relaxation") and so on?

**Comment by wildart** [comment]
Sure, why not? New stuff is always welcome. On the downside, it might get a bit longer to review your PR as there isn't much of the volunteer time available.

You need also to evaluate what dependencies will be required for your implementation. The package is designed to be lightweight, and I do not think we'll extend beyond available once. Meaning, if you need Optim or JuMP, you'll be better with standalone package. I glanced through the REAPER paper, and it seems possible to implemented it within the above constraint.

**Comment by nobuta05** [comment]
Thank you for your reply. I'm glad to get your positive feedback. I wondered if robust methods should be separated from the standard statistics library or not because this field is vast. As far as I know, there are 10 more robustified PCA methods.

I agree with the design that lightweight is important. I'll submit a PR in line with the idea soon. Thank you very much.
