### ISSUE TITLE
Memory-efficient LDA

### ISSUE THREAD

**Issue by timholy** [JuliaStats/MultivariateStats.jl#13]
I am not very familiar with this package, but it appears that by default this package's LDA routines store the full covariance matrix associated with each point. If your points are, say, an image (living in a 10^6-dimensional space), that covariance matrix will be large.

There's a more memory-efficient alternative: one can demonstrate that the eigenvectors lie in the subspace spanned by the class means, and so consequently if there are `n` classes, really the LDA should be performed on an `n-1`-dimensional projection of the underlying data points. Note that this is better than first doing a PCA to reduce the dimensionality, in the sense that PCA is going to pick dimensions based on the total sample variance and may not return a projection as useful as the one based on the class means.

I'm not sure how to fit this in with the framework in this package, but there's an implementation [here](https://github.com/JuliaGraphics/Immerse.jl/blob/2f3aa049d09e58af44790d83e65752eddc121caf/test/faces_utilities.jl#L18-L97). I'm offering to donate it to MultivariateStats, but I'd like a collaborator on the integration. (Or just go steal it and package it how you like.)

**Comment by jiahao** [comment]
@timholy do you have a sense for how many principal components survive the thresholding? If it's ~20% or fewer then it might make sense to use an iterative SVD algorithm. `IterativeSolvers.svdvals_tr` is good enough for production use once I add the code to return singular vectors. I currently don't have an implementation that computes all the singular values over some threshold, but it shouldn't be too hard to implement.

**Comment by timholy** [comment]
We may be talking about two different things here, but in this case there's no "real" threshold: analytically, the eigenvectors lie exactly on the subspace spanned by the means. The threshold I used was there just to handle degenerate cases, and is basically a roundoff error check.

**Comment by jiahao** [comment]
I meant if [`ikeep`](https://github.com/JuliaGraphics/Immerse.jl/blob/2f3aa049d09e58af44790d83e65752eddc121caf/test/faces_utilities.jl#L29) is significantly shorter than either dimension `dmeans` in practice. I guess not.

**Comment by timholy** [comment]
Right, `sum(ikeep)` is usually 1 less than the number of columns in `dmeans` (which is in such applications much smaller than the number of rows in `dmeans`).

**Comment by timholy** [comment]
PR coming
