### ISSUE TITLE
ERROR: MethodError: no method matching PCA()

### ISSUE THREAD

**Issue by casasgomezuribarri** [JuliaStats/MultivariateStats.jl#132]
I am following the MLJ tutorials, and ran into an issue with [this one](https://alan-turing-institute.github.io/DataScienceTutorials.jl/isl/lab-10/) about PCA and Clustering. 

I am trying to run this piece of code from the [first section](https://alan-turing-institute.github.io/DataScienceTutorials.jl/isl/lab-10/#pca_pipeline):
 

> @load PCA pkg=MultivariateStats
> 
> pca_mdl = PCA(pratio=1)
> pca = machine(pca_mdl, X)
> fit!(pca)
> PCA
> W = transform(pca, X);

And, although the first line is evaluated normally, all the other lines give back an error, which has its origin on the second line not being evaluated. This is the corresponding error:

> ERROR: MethodError: no method matching PCA()
> Closest candidates are:
>   PCA(::Array{T,1}, ::Array{T,2}, ::Array{T,1}, ::T) where T<:Real at C:\Users\ivica\.julia\packages\MultivariateStats\BYMwD\src\pca.jl:16
>   PCA(::Array{T,1}, ::Array{T,2}, ::Array{T,1}, ::T, ::T) where T<:Real at C:\Users\ivica\.julia\packages\MultivariateStats\BYMwD\src\pca.jl:6      
> Stacktrace:
>  [1] top-level scope at REPL[1]:1

From comparison with the implementation of other learning algorithms, the syntax is consistent with the rest of the package, for example:

> dtr_model = DecisionTreeRegressor()

I am not sure if this is an issue of MultivariateStats.jl or MLJ.jl, but I am more inclined to think this is the right place to post because all the other learning algorithms work fine.

Appreciate any help, thanks!

**Comment by nalimilan** [comment]
I'd say it's an MLJ issue. Their docs mention that method but it doesn't exist, so...

**Comment by casasgomezuribarri** [comment]
Thanks for the advice. If anyone is running into this problem too, they can follow up the issue at MLJ.jl using [this link](https://github.com/alan-turing-institute/MLJ.jl/issues/699)
