### ISSUE TITLE
Refresh the documentation

### ISSUE THREAD

**Issue by julien-blanchon** [JuliaStats/MultivariateStats.jl#137]
The PCQ page seems not update since there are still some usage of deprecated `DataArray` type -> https://multivariatestatsjl.readthedocs.io/en/latest/pca.html.
But the corresponding srt seems correct: https://github.com/JuliaStats/MultivariateStats.jl/blob/master/docs/source/pca.rst
Maybe recompiling the website will solve the doc

**Comment by wildart** [comment]
New docs are here: https://juliastats.org/MultivariateStats.jl/stable/
