### ISSUE TITLE
Less restrictive types for reconstruct

### ISSUE THREAD

**Issue by Kolaru** [JuliaStats/MultivariateStats.jl#139]
Currently reconstruct for PCA have the following signature:

```julia
reconstruct(M::PCA{T}, y::AbstractVecOrMat{T}) where {T<:Real}
```

This can be slightly annoying if the PCA was fitted with Float32 (e.g. data loaded from some file for which it is standard) and then the `y` is generated independantly thus being Float64 and leading to `MethodError`.

Could these kind of restrictions be lifted? If yes I'll look into a PR for it.

**Comment by wildart** [comment]
Sure, `transform` & `reconstruct` can be mended to accept different parameter types. If you up to, PR is always welcome.

**Comment by wildart** [comment]
Thanks for fix.
