### ISSUE TITLE
Multidimensional scaling (MDS) point order

### ISSUE THREAD

**Issue by asdrsdg** [JuliaStats/MultivariateStats.jl#149]
Hi, I'm using the MDS functionality which takes as input a distance matrix and returns a projection of points with said distance matrix in, e.g., 2D.

However I can't find a mention on how is the outputted point set ordered (of MultivariateStats.classical_mds). Could you please confirm whether the ordering of the points is the same as the ordering of, e.g., columns in the distance matrix? And perhaps add it to the documentation?

It is important to know this when, e.g., you have 2D set of points with data about specific people where 70% of columns in the distance matrix are men and 30% are women. When you input this distance matrix into classical_mds, is the ordering of the output points the same as in the distance matrix? In other words, is the first 70% of points from the classical_mds output the projection of men data and the remainning 30% women data?

I tried generating some points to see whether the ordering is preserved and it seems so but having it confirmed would help!

Thanks!

**Comment by wildart** [comment]
Yes, points in a resulting transformation are in the same order as corresponding columns/rows in a distance matrix.
