### ISSUE TITLE
Support DataFrames

### ISSUE THREAD

**Issue by cyocum** [JuliaStats/MultivariateStats.jl#15]
At the moment, I am trying to plot some information on some texts and it would be great if I could have this package support doing this with DataFrames so I can attempt to keep track of the titles of the texts and plot them out on a graph using Gadfly so I can actually is what is going on with the data.

**Comment by ararslan** [comment]
A lot of packages, particularly those in the stats ecosystem, could benefit from tighter integration with DataFrames. However, it's a fairly heavy-weight dependency, so until there's support for optional dependencies, we're unlikely to make this change.
