### ISSUE TITLE
classical_mds() could return eigenvalues

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/MultivariateStats.jl#16]
Could you please consider returning the eigenvalues in addition to the eigenvectors? They contain valuable information.

**Comment by jiahao** [comment]
All you have to do is return `v` in `classical_mds`. I think it would make sense to have a new keyword argument to ask for the eigenvalues.

**Comment by juliohm** [comment]
I would say the eigenvalues should always be returned like cmdscale() in MATLAB. It gives the user the freedom to choose how many dimensions to keep. Right now the user has no idea of how reliable is the dimensionality reduction.

**Comment by juliohm** [comment]
@jiahao do you agree? Should the function return the full set of eigenpairs and let the user decide?

This is a good example of usage by MathWorks: http://www.mathworks.com/help/stats/examples/classical-multidimensional-scaling.html

**Comment by jiahao** [comment]
Most numerical routines I've used and have written usually have a default output mode that produces just what the user wants, and an extended output mode with detailed numerical output that can be triggered as an optional keyword argument.

**Comment by juliohm** [comment]
I like this idea in general. Keep things simple and clear whenever you can.

What do you suggest? Can you handle this improvement in the API yourself? I
can reserve some time to fix it in the future. Really busy now with my
proposal defense.

If you can work on that it would help me on my research immediately. :) I
don't wanna resort to MATLAB or any other language.

-Júlio

**Comment by jiahao** [comment]
I'm busy with other things at the moment, but as I've said, for your purposes it would suffice for now to modify `classical_mds` to return `v` as well as `U'`. It would make sense to make returning `U'` and `v` the output when specifying, say, `verbose=true` .

Good luck with your proposal defense!

**Comment by juliohm** [comment]
Besides returning the highest eigenvalues we also need to return all the
others. I'll check the code later, thanks!

-Júlio

**Comment by juliohm** [comment]
By seeing this as mainly a visualization technique, people may not be very interested in having the eigenvalues exported anyways. I am closing the issue.
