### ISSUE TITLE
ICA algorithm seems wrong

### ISSUE THREAD

**Issue by tomhaber** [JuliaStats/MultivariateStats.jl#160]
I was reading the ICA implementation and noticed that this line is in the wrong place:
https://github.com/JuliaStats/MultivariateStats.jl/blob/f00cba303eb363d5a61fdc74895e24db196da9c1/src/ica.jl#L97

It should probably be inside the for loop

**Comment by wildart** [comment]
Looks like a bug. Thanks.

**Comment by wildart** [comment]
Fixed in #174
