### ISSUE TITLE
Stable documenter docs are not building

### ISSUE THREAD

**Issue by rafaqz** [JuliaStats/MultivariateStats.jl#161]
The dev badge works, stable doesn't. Maybe there's an issue with documenter keys?

**Comment by wildart** [comment]
I'm preparing for a point release, because there were some substantial changes.

**Comment by timholy** [comment]
I love some of the features in the `dev` branch. What are the remaining roadblocks for making a release?

**Comment by wildart** [comment]
Mainly, it's documentation refactoring - moving rts docs to docstrings.

**Comment by wildart** [comment]
Docs are available now.
