### ISSUE TITLE
StackoverflowError

### ISSUE THREAD

**Issue by Roh-codeur** [JuliaStats/MultivariateStats.jl#164]
Hi

ran the below code and it threw a StackoverflowError

`        σ = 0.5`
`       model = fit(`
`            KernelPCA,`
`            array;`
`            kernel = (x, y) -> x'y + exp(-norm(x - y)^2 / (2 * σ^2)),`
`            maxoutdim = numFactors,`
`            inverse = true,`
`        )`

`ERROR: StackOverflowError:`

MLDataUtils v0.5.4
MLJ v0.16.11
MultivariateStats v0.8.0
ScikitLearn v0.6.4
StatsBase v0.33.13
LinearAlgebra
Statistics

Worked fine on Julia 1.6 on my Intel Mac. Ran this on Julia 1.7 on my M1 Mac. Looks like this is related to the upgrade to Apple M1. any idea how I can diagnose, workaround or a fix?

thanks!

**Comment by wildart** [comment]
Anything else in the error message? The exception trace should point to the problem. However, I doubt that the error relates to this package. There is no recursive calls to trigger overflow.

**Comment by Roh-codeur** [comment]
Nope, nothing else I am afraid.

**Comment by wildart** [comment]
How big is the dataset? Kernel representation takes square of the dataset size. Can you run the same example with the random data of the same size?

**Comment by Roh-codeur** [comment]
tried the below code: 

`using MultivariateStats, RDatasets`

`# load iris dataset`
`iris = dataset("datasets", "iris")`

`Xtr = Matrix(iris[!,1:4])'`
`Xtr_labels = convert(Array, iris[!,5])`

`model = fit(`
`    KernelPCA,`
`   Xtr;`
`    kernel = (x, y) -> x'y,`
`   maxoutdim = 3,`
`    inverse = true,`
`)`

Error:
`ERROR: LoadError: StackOverflowError:`

**Comment by Roh-codeur** [comment]
It works fine with Julia 1.7.1

https://discourse.julialang.org/t/package-for-kpca/74248
