### ISSUE TITLE
PCA example throws error

### ISSUE THREAD

**Issue by rkube** [JuliaStats/MultivariateStats.jl#166]
Hi, 
I'm trying to run the PCA example for the IRIS code but get an error when calling predict:
```
julia> M = fit(PCA, Xtr; maxoutdim=3)
PCA(indim = 4, outdim = 3, principalratio = 0.9957325846529407)

julia> Yte = predict(M, Xte)
ERROR: MethodError: no method matching predict(::PCA{Float64}, ::LinearAlgebra.Adjoint{Float64, Matrix{Float64}})
Closest candidates are:
  predict(::Discriminant, ::AbstractMatrix{T} where T) at /home/rkube/.julia/packages/MultivariateStats/HTpHt/src/lda.jl:26
Stacktrace:
 [1] top-level scope
```

Does anyone know what is going on here?

**Comment by wildart** [comment]
Which version are you using? What is your julia version? I cannot reproduce this error on 1.6.4 & 1.7.1.

**Comment by smartinsightsfromdata** [comment]
@rkube   The error is relative to a conflict between `MultivariateStats` and `RDatasets` on the keyword `transform`.
Change it as:
```
Yte = MultivariateStats.transform(M, Xte)
```

(but there are errors further down in the example that I haven't been able to solve - I'll create an issue on it)

**Comment by wildart** [comment]
The example has been updated in the new documentation. Please, [take a look](https://juliastats.org/MultivariateStats.jl/stable/pca/#Example).
