### ISSUE TITLE
Type restriction on ICA

### ISSUE THREAD

**Issue by vchuravy** [JuliaStats/MultivariateStats.jl#19]
Fitting on ICA is currently defined as `fit(::ICA, X::DenseMatrix{Float64}, k::Int64)` [1]

But `Matrix{Float64} <: DenseMatrix{Float64}`, so calling `fit` on ICA is not possible at all.

[1] https://github.com/JuliaStats/MultivariateStats.jl/blob/04dc53d361199569f9a1db63cbcf90d0189b26ac/src/ica.jl#L151

**Comment by wildart** [comment]
Not relevant anymore.
