### ISSUE TITLE
`transform` and `reconstruct`

### ISSUE THREAD

**Issue by gdkrmr** [JuliaStats/MultivariateStats.jl#190]
I got a bit confused trying to figure this out myself: Is release 1.0 going to use `StatsBase.transform` and `StatsBase.reconstruct` or are you going to use `transform` and `reconstruct` from somewhere else?

https://github.com/JuliaStats/StatsBase.jl/issues/781#issuecomment-1091428363

**Comment by wildart** [comment]
`StatsBase.transform` & `StatsBase.reconstruct` are internal function, they are not exported. `MultivariateStats` reexports `fit` & `predict` that are defined in StatsAPI package. `predict` call does the same job which is previously  `transform` did, i.e. the function forms the response of a given model. The `reconstruct` function is exported explicitly in `MultivariateStats`, Thus, you have  `fit`, `predict`, and `reconstruct` as a core API functions for this package,
