### ISSUE TITLE
Request for adjoint support in MulticlassLDA

### ISSUE THREAD

**Issue by ablaom** [JuliaStats/MultivariateStats.jl#192]
```julia
 MethodError: no method matching fit(::Type{MultivariateStats.MulticlassLDA}, ::Int64, ::Adjoint{Float64, Matrix{Float64}}, ::Vector{Int64}; method=:gevd, outdim=1, regcoef=1.0e-6, covestimator_within=SimpleCovariance(false), covestimator_between=SimpleCovariance(false))
```
I realize I'm better off passing a regular matrix, but it'd be good to have this. Some context: https://github.com/JuliaAI/MLJMultivariateStatsInterface.jl/issues/27

**Comment by ablaom** [comment]
@wildart 🙏🏾

**Comment by ablaom** [comment]
@wildart Thanks for this. Unfortunately, I can't figure out from the 0.10 release notes what the breaking changes are. Do you happen to know?

**Comment by wildart** [comment]
Major things are metric MDS & changes in Multi-class & Subspace LDA function signatures (no more explicit number of classes parameter)
