### ISSUE TITLE
fit() method fails for Matrices with `Float32` element type

### ISSUE THREAD

**Issue by AzamatB** [JuliaStats/MultivariateStats.jl#20]
The following code fails:
`fit(PCA, rand(Float32, 3,3))`

**Comment by andreasnoack** [comment]
This should work on latest master so try `Pkg.checkout("MultivariateStats")`. I've also just opened #21 which will make the package work on the development version of Julia. When that has been merged, I plan to tag a new version of the package.

**Comment by AzamatB** [comment]
Great! Thanks!

**Comment by andreasnoack** [comment]
I've just tagged a new version https://github.com/JuliaLang/METADATA.jl/pull/4652 so in a day or two `Pkg.update()` should also be sufficient.
