### ISSUE TITLE
SVD and LAPACK

### ISSUE THREAD

**Issue by alancrawford** [JuliaStats/MultivariateStats.jl#22]
Hi,

While doing:

M = MultivariateStats.fit(PCA,Xsc; method=:svd, mean=0, pratio = 0.99)

where Xsc is a scaled and centred matrix. I am being thrown the following error:

ERROR: LoadError: Base.LinAlg.LAPACKException(12)
 in gesdd! at linalg/lapack.jl:1482
 in svdfact! at linalg/svd.jl:17
 in svdfact at linalg/svd.jl:23
 in pcasvd at /.julia/v0.4/MultivariateStats/src/pca.jl:118

I am assuming that the matrix itself might be the problem and i am trying to take remedial action. However, I am unable to track down/interpret the error. Any help greatly appreciated

Thanks
Alan

**Comment by simonbyrne** [comment]
Do you have a reproducible example?

**Comment by alancrawford** [comment]
I have pulled the example of the loop that creates the data for the PCA. This was a useful exercise as I can see that it is produced NaNs in the matrix to which PCA would be applied. I assume this is the root cause of the problem. 

I guess it would be useful to have slightly more detailed error messages (not sure this is possible?), but that is a more general comment and will close this issue. Thanks, Alan.

**Comment by nalimilan** [comment]
> I guess it would be useful to have slightly more detailed error messages (not sure this is possible?), but that is a more general comment and will close this issue. Thanks, Alan.

Please file an issue in Julia with a reproducible example. Something as common as failure due to the presence of `NaN` should indeed lead to a more explicit error message.

**Comment by simonbyrne** [comment]
see https://github.com/JuliaLang/julia/issues/4836
