### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dreammaker** [JuliaStats/MultivariateStats.jl#27]
Hi, can you make a new release of this and publish it to METADATA?  In particular, we're trying to track down some precompile issues in our project, and we're trying to get all our dependencies precompiled.  I see that `__precompile__()` was recently committed, but it hasn't been released.  Thanks.

**Comment by ararslan** [comment]
I can do this later today if no one beats me to it.

**Comment by ararslan** [comment]
Done
