### ISSUE TITLE
Julia 0.5.2 syntax: invalid character "‰"

### ISSUE THREAD

**Issue by finmod** [JuliaStats/MultivariateStats.jl#35]
Trying this command on ppca.jl with Juliav0.5.2, the character for approximately equal or some other forms of equal is not recognized in a ipynb.

@test transform(M, X[:,1]) â‰ˆ T * (X[:,1] .- mv) and all the others with â‰ˆ give:

syntax: invalid character "‰"

Pkg.test("MultivariateStats") passed.

**Comment by ararslan** [comment]
This isn't related to this package. Also I don't know if those characters aren't displaying properly for me or if they ended up weird in Jupyter, but `‰` is definitely not an equality symbol. The best way to get what you're after is using LaTeX command completion. In this case you probably want `\approx` then press <kbd>tab</kbd>.

**Comment by finmod** [comment]
Thank you. \approxTab works.
