### ISSUE TITLE
Warning if (e.g. fastica!) does not converge?

### ISSUE THREAD

**Issue by alexmorley** [JuliaStats/MultivariateStats.jl#36]
Would anyone else find it useful to have a warning if iterable algorithms are hitting `maxiter` instead of reaching `tol`? Could have another kwarg to turn this behaviour on/off. Happy to make PR if anyone thinks its a good idea.

**Comment by nalimilan** [comment]
+1

GLM.jl throws a `ConvergenceException` in that case. It's defined in StatsBase so that other packages can use it. It would make sense to throw by default so that people don't mistakenly use models with incorrect results.

**Comment by alexmorley** [comment]
OK I will make a PR for this now.
