### ISSUE TITLE
Add Kernel PCA

### ISSUE THREAD

**Issue by juliohm** [JuliaStats/MultivariateStats.jl#41]
This would be a great addition to the package.

**Comment by alexmorley** [comment]
If you need it for now easy to use via ScikitLearn.jl (https://github.com/cstjean/ScikitLearn.jl/blob/master/docs/pipelines.md)

**Comment by juliohm** [comment]
Thanks @alexmorley, and thank you for working on it, I am looking forward for a pure Julia version. :+1:

**Comment by ararslan** [comment]
Added in #43.
