### ISSUE TITLE
[Kernel PCA] pairwise! function and kernel centering

### ISSUE THREAD

**Issue by zgornel** [JuliaStats/MultivariateStats.jl#44]
Hello,

In Kernel PCA the `pairwise!` function does not work when generating non-symmetric kernels:
```julia
julia> MultivariateStats.pairwise((x,y)->x'y,[1.0 2 3],[1.0 2.0 3.0 4.0 5.0])                                                                                                                  
#3×5 Array{Float64,2}:                                                                                                                                                                          
#1.0  2.0  3.0  6.95024e-310  6.95024e-310                                                                                                                                                     
#2.0  4.0  6.0  6.95024e-310  6.95024e-310                                                                                                                                                     
#3.0  6.0  9.0  6.95024e-310  6.95024e-310 
```
Also, kernel centering may not be necessary when transforming (line 50 in `kpca.jl`). As I am not very familiar with Kernel PCA, I based my assumption on [this](http://www.cs.haifa.ac.il/~rita/uml_course/lectures/KPCA.pdf) and the fact that the centering code works on symmetric kernels only. 

On a non-symmetric kernel, for testing data with more samples than the training data, the inner for loop fails as the second dimension of the input kernel matrix (i.e. the number of input test samples) is larger than the means vector `C.means`.

Best regards,

**Comment by wildart** [comment]
Usually, kernels are finitely positive semi-definite functions, `k : X * X -> R`, so resulting kernel matrix should be positive semi-definite matrix. Your example is incorrect because two last arguments of the  `MultivariateStats.pairwise` should be of the same dimension.

If you need to use a non-symmetric kernel `K`, form a positive definite matrix from it as `K'K` and use it as precomputed kernel.

**Comment by zgornel** [comment]
Thank you for the repy; `pairwise` is used both in the `fit` and `transform` methods; unless testing data is required to have the same number of samples as the training data, the example is correct.

**Comment by wildart** [comment]
You do not need to precompute the kernel matrix in advance, just use `fit` call with your training data.
```julia
M = fit(KernelPCA, X_training, kernel=(x,y)->x'y) 
```
If you want to use the precomputed kernel `K` then `fit` call is following
```julia
M = fit(KernelPCA, K, kernel=nothing)
```
You can use any kernel function for creating the kernel matrix, but make sure that the resulting matrix is positive definite.

`MultivariateStats.pairwise` make a  symmetric matrix by from columns of your data matrix, so you should make following call.

```julia
julia> MultivariateStats.pairwise((x,y)->x'y,[1.0 2 3])
3×3 Array{Float64,2}:
 1.0  2.0  3.0
 2.0  4.0  6.0
 3.0  6.0  9.0
```
> unless testing data is required to have the same number of samples as the training data, the example is correct.

Not quite, see below, my training data is composed of 10 5-dimensional observations in `X`, and the testing data just have 5 observations in `Y` 

```julia
julia> X = randn(5, 10)
5×10 Array{Float64,2}:
 -0.0781806   2.60082   -0.165623   -0.419282   -2.23824   -1.12588     0.635245  -0.288235  -0.536034  -0.961028
 -1.1305      1.10886   -2.91188    -1.16896    -0.666798  -0.816821    0.745129  -0.878112   0.390659   0.81176 
  0.796578    1.03518   -0.943569    0.785266   -0.024068  -0.0143219   0.123476   0.161169   0.558555  -1.31485 
  0.82246    -1.12491    0.0956753   0.0665878  -1.02155    0.837077   -1.27162   -0.491935  -0.863232  -0.728546
  0.716065   -0.621793  -1.03971    -1.11068     0.36305   -0.823006   -0.543686  -0.885005  -0.162099   0.888264

julia> Y = randn(5, 5)
5×5 Array{Float64,2}:
  1.16688   -1.00092    0.925586  -0.391542  -0.167246
 -1.65607   -0.220732   0.674343  -1.39586    0.605282
 -0.260539  -0.747368   0.777678  -0.509077   0.269422
 -0.710508  -0.77255   -2.02473   -0.864199  -0.196568
 -0.778249  -0.757166  -1.1143     1.7609     0.758735

julia> M = fit(KernelPCA, X, maxoutdim = 5)
Kernel PCA(indim = 5, outdim = 5)

julia> Z = transform(M, Y) # here we do the transformation of the testing data
5×5 Array{Float64,2}:
 -0.143888   0.482343  -1.23537   -0.13877   -0.880339
 -1.51508    0.56109   -0.120056   0.738828   0.146955
  1.03073   -0.300861  -1.98705   -0.557591  -0.261804
  0.445962   0.697395   1.06748    1.41      -0.161922
  0.60832    0.424208   1.9984     1.661     -0.127804
```

**Comment by zgornel** [comment]
Try using ```Y = rand(5,20)```

**Comment by wildart** [comment]
Ah, it's a bug.
