### ISSUE TITLE
LDA Method Error

### ISSUE THREAD

**Issue by jjhincapief** [JuliaStats/MultivariateStats.jl#50]
Hi there, 

I'm having an issue regarding the fit function. When I try to run fit(LinearDiscriminant, [1 2 3 4].  [5 6 7 8]) I get a Method Error saying no method matching LinearDiscriminant.

**Comment by wildart** [comment]
Currently `LinearDiscriminant` implementation accepts only floating-point data as input.
``` julia
julia> fit(LinearDiscriminant, [1 2 3 4.], [5 6 7 8.])
MultivariateStats.LinearDiscriminant{Float64}([-0.5], 2.25)
```

**Comment by jjhincapief** [comment]
Thank you
