### ISSUE TITLE
Any plans for stress evaluation of MDS?

### ISSUE THREAD

**Issue by shze** [JuliaStats/MultivariateStats.jl#51]
Are there any plans to implement functions that allow to evaluate the stress of an MDS solution?

**Comment by nico202** [comment]
Any way this https://github.com/wildart/MultivariateStats.jl/commit/c1eae0930b557abb69cd5e3d9ad9368d71793d69#diff-80b30b32f11a4e83967dde065e68c832 will be marged?

**Comment by wildart** [comment]
In a couple of weeks.
