### ISSUE TITLE
Implement PCoA (principal coordinate analysis)

### ISSUE THREAD

**Issue by kescobo** [JuliaStats/MultivariateStats.jl#58]
Principal coordinate analysis is essentially a PCA with some transformations that make it suitable for non-metric distances where negative eigen values can be generated. It's often used in ecology for visualizing dissimilarity between different sites for example (see [here](https://doi.org/10.1007/BF02291398) for a paper describing it and an [R package](https://www.rdocumentation.org/packages/ape/versions/5.0/topics/pcoa) that implements it).

I've written [an implementation](https://github.com/BioJulia/Microbiome.jl/blob/master/src/similarity.jl) for my microbiome package, but thought it might be more generally useful. I also suspect with code review from the community it will end up far better than what I've written on my own (I'm by no means an expert on linear algebra).

So I wanted to know if that code/should could be ported over here. I've verified on several matrices that my code generates the same results as the R package linked above, but I'm sure it could be made much more efficient and cleaned up a lot, with some help.

**Comment by wildart** [comment]
Package already has an implementation of classical MDS. Take a look at it.

**Comment by kescobo** [comment]
As evidence for how non-expert I am, I forgot classical MDS is the same thing :-/

I will check it out and see if I can replace my implementation with that. Thanks!

**Comment by kescobo** [comment]
Actually - after looking at the docs for classical mds, I now recall that I originally did plan to use  this implementation. There are a couple of things that I needed that are missing though.

1) the eigenvalues used to transform the matrix (I think the code [here](https://github.com/JuliaStats/MultivariateStats.jl/blob/master/src/cmds.jl#L107) just pulls the vectors from `eigfact()` and discards the values

2) methods for transforming the matrix if the solution has negative eigenvalues. There are two methods described by the R package above, and I've implemented the "Lignoes" version, which is just to subtract the absolute value for most negative eigenvalue from all cells of the gram matrix and re-do the scaling. There's also the "Calliez" correction ([see here](https://doi.org/10.1007/BF02294026)), but I could not grok it at the time, so skipped it. 

If there's interest, I'd be happy to work on integrating these here. If not, no worries!

**Comment by wildart** [comment]
Any improvement are quite welcome.

> the eigenvalues used to transform the matrix (I think the code here just pulls the vectors from eigfact() and discards the values

One way to address this problem is to implement `fit` function which would return a model object with required data.

> methods for transforming the matrix if the solution has negative eigenvalues.

That can be addressed by providing argument for particular correction algorithm. Look at how PCA is implemented with various methods.

**Comment by kescobo** [comment]
@wildart Thanks for the suggestions! I'll take a look and see what I can do. Is the best way to move forward to just open a PR when I have something to show?

**Comment by wildart** [comment]
Start with submitting a PR with improvements, and we'll discuss implementation aspects.

**Comment by kescobo** [comment]
I was just about to finally return to this (only 18 months late), pulled the latest version, set up a development environment to poke around in, only to notice you *just* took care of this in #85. Thank you!
