### ISSUE TITLE
JuliaBox Package unresolved

### ISSUE THREAD

**Issue by mcbaron** [JuliaStats/MultivariateStats.jl#78]
This might be related to #73.
In JuliaBox with a 1.0.0 kernel, running 
` Pkg.add("MultivariateStats"); using MultivariateStats` 
results in the error: 
 ```
The following package names could not be resolved:
 * MultivariateStats (not found in project, manifest or registry)
Please specify by known `name=uuid`. 
```

**Comment by mcbaron** [comment]
Sorry, why was this closed?

**Comment by wildart** [comment]
Julia 0.7/1.0 compatible version of this package has been tagged some time ago. Try to install the package again. If the error persists, reopen this issue as well as in JuliaBox repo.
