### ISSUE TITLE
standardize data before pca

### ISSUE THREAD

**Issue by gdkrmr** [JuliaStats/MultivariateStats.jl#86]
Currently there is no way to standardize data when doing a PCA, only to centralize.

**Comment by wildart** [comment]
Usually, you would standardize data prior to fitting and do not mix two operations together. It's better not to mix two operations together.

FYI, there is data transformation PR pending: https://github.com/JuliaStats/StatsBase.jl/pull/85

**Comment by gdkrmr** [comment]
you should probably allow something like:
```julia
x = rand(3, 10)
z = fit(ZScoreTransform, x)
p = fit(PCA, transform(z, x))
transform((z, p), xnew)
```
or maybe even make the objects callable:
```julia
xnew |> z |>  p
```
and for the reconstruction:
```julia
y |> inv(p) |> inv(z)
```

**Comment by wildart** [comment]
>What about the centering step, are you going to remove that?

No, not really.

Transformation and reconstructions are following:
```julia
x = rand(3, 10)
# standardize data
T = fit(ZScoreTransform, x)
xstd = transform(Z, x)
# perform PCA
M = fit(PCA, xstd)
ysub = transform(M, xstd)
# reconstruct to original space
ystd = reconstruct(M, ysub)
# reconstruct to original scale
y = reconstruct(T, ystd)
x ≈ y
```

Even thought pipeline `X |> ZScoreTransform  |>  PCA` looks appealing. It is beyond the scope of this package.

**Comment by gdkrmr** [comment]
> > What about the centering step, are you going to remove that?
> 
> No, not really.

This seems like an arbitrary choice.
