### ISSUE TITLE
Change warn to at-warn for Julia 1.0 compatibility

### ISSUE THREAD

**Issue by nico202** [JuliaStats/MultivariateStats.jl#91]
There are a couple of warn that should be @ warn like here: 
https://github.com/JuliaStats/MultivariateStats.jl/blob/ca576a4be492afb48dfa33e6afd74402d01c3043/src/cmds.jl#L92
and https://github.com/JuliaStats/MultivariateStats.jl/blob/ca576a4be492afb48dfa33e6afd74402d01c3043/src/cmds.jl#L105

**Comment by ararslan** [comment]
Would you be willing to submit a PR for this?

**Comment by nico202** [comment]
Sorry I missed the notification. Sure
