### ISSUE TITLE
transform(kpca) returns error

### ISSUE THREAD

**Issue by gdkrmr** [JuliaStats/MultivariateStats.jl#96]
```
using MultivariateStats
data = randn(3, 100)
kpca = fit(KernelPCA, data)
transform(kpca) # error
transform(kpca, data) # works 
```

**Comment by wildart** [comment]
`transform(kpca)` only works with precomputed kernels. There should be more comprehensive error for this call.

**Comment by gdkrmr** [comment]
How do I get the embedded coordinates of my original data points then?

**Comment by wildart** [comment]
As you wrote above:
```julia
original = randn(3, 100)
model = fit(KernelPCA, original)
embedded = transform(model, original) 
```

**Comment by gdkrmr** [comment]
that is quite inefficient, because `transform(kpca, X)` calculates the  kernel matrix again,  this could be avoided with:
```julia
transform(kpca::KernelPCA) = sqrt.(kpca.λ) .* kpca.α'
```

**Comment by wildart** [comment]
You are right, I completely disregarded that. Fix is coming.
